
int bitAnd(int, int);
int test_bitAnd(int, int);
int getByte(int, int);
int test_getByte(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int bitCount(int);
int test_bitCount(int);
int bang(int);
int test_bang(int);
int tmin();
int test_tmin();
int absVal(int);
int test_absVal(int);
int fitsShort(int);
int test_fitsShort(int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int negate(int);
int test_negate(int);
int isPositive(int);
int test_isPositive(int);
int ilog2(int);
int test_ilog2(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
